name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 當 main 分支有變動時自動執行

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Vite 編譯後的資料夾
          branch: gh-pages # 自動將網頁打包到這個分支
